services:
  php:
    build: .
    volumes:
      - .:/app
    ports:
      - 9502:9502
  websocket:
    build: .
    volumes:
      - .:/app
    ports:
      - 9502:9502
    entrypoint: ["php", "src/index.php"]